plugins {
    id 'java-library'
    id 'maven-publish'
    id 'idea'
    id 'net.neoforged.moddev' version '2.0.141'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
    gradleVersion = '9.1.0'
}

version = mod_version
group = mod_group_id

base {
    archivesName = "${mod_id}-${minecraft_version}"
}

sourceSets.main.resources {
    srcDir('src/generated/resources')
}

repositories {
    exclusiveContent {
        forRepository {
            maven {
                name = 'BlameJared'
                url = 'https://maven.blamejared.com'
            }
        }
        filter {
            includeGroup 'com.hrznstudio'
            includeGroup 'mezz.jei'
        }
    }
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

neoForge {
    version = "${neo_version}"
    //accessTransformers.add(file('src/main/resources/META-INF/accesstransformer.cfg'))
    runs {
        client {
            client()
        }
        server {
            server()
        }
    }

    mods {
        purradox {
            sourceSet sourceSets.main
        }
    }

}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    implementation "com.hrznstudio:titanium:${titanium_version}"
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            titanium_version       : titanium_version,
            titanium_version_range : titanium_version_range,
    ]

    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }

    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
