org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.94
titanium_version=26.1.2-4.0.1
titanium_version_range=[4.0.1,)

mod_id=purradox
mod_name=Purradox
mod_license=MIT
mod_version=0.0.0
mod_group_id=com.purradox
